### ISSUE TITLE
NPE with CDI-Events

### ISSUE THREAD

**Issue by HRE** [tomivirkki/cdiutils#5]
I've had a NullPointerException when listening for Events with @Observes(notifyObserver = Reception.IF_EXISTS)

**Comment by HRE** [comment]
Stack Trace Excerpt:

```
java.lang.NullPointerException: null
at org.vaadin.virkki.cdiutils.application.VaadinContext$BeanStore.getBeanInstance(VaadinContext.java:241) ~[org.vaadin.addons.cdi-utils.jar:0.9.9]
at org.vaadin.virkki.cdiutils.application.VaadinContext$ApplicationBeanStore.getBeanInstance(VaadinContext.java:144) ~[org.vaadin.addons.cdi-utils.jar:0.9.9]
at org.vaadin.virkki.cdiutils.application.VaadinContext$VaadinContextImpl.doGet(VaadinContext.java:104) ~[org.vaadin.addons.cdi-utils.jar:0.9.9]
at org.vaadin.virkki.cdiutils.application.VaadinContext$VaadinContextImpl.get(VaadinContext.java:74) ~[org.vaadin.addons.cdi-utils.jar:0.9.9]
at org.jboss.weld.manager.BeanManagerImpl.getReference(BeanManagerImpl.java:637) ~[weld-osgi-bundle.jar:20120429-1045]
at org.jboss.weld.event.ObserverMethodImpl.getReceiverIfExists(ObserverMethodImpl.java:256) ~[weld-osgi-bundle.jar:20120429-1045]
at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:225) ~[weld-osgi-bundle.jar:20120429-1045]
at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:213) ~[weld-osgi-bundle.jar:20120429-1045]
at org.jboss.weld.manager.BeanManagerImpl.notifyObservers(BeanManagerImpl.java:590) ~[weld-osgi-bundle.jar:20120429-1045]
at org.jboss.weld.manager.BeanManagerImpl.fireEvent(BeanManagerImpl.java:585) ~[weld-osgi-bundle.jar:20120429-1045]
at org.jboss.weld.event.EventImpl.fire(EventImpl.java:69) ~[weld-osgi-bundle.jar:20120429-1045]
```

**Comment by HRE** [comment]
The following patch resolved my issues:

```
Index: org/vaadin/virkki/cdiutils/application/VaadinContext.java
===================================================================
--- org/vaadin/virkki/cdiutils/application/VaadinContext.java
+++ org/vaadin/virkki/cdiutils/application/VaadinContext.java
@@ -233,10 +233,14 @@
                 final CreationalContext<T> creationalContext) {
             ContextualInstance<T> contextualInstance = (ContextualInstance<T>) instances
                     .get(bean);
-            if (contextualInstance == null && creationalContext != null) {
-                contextualInstance = new ContextualInstance<T>(
+            if (contextualInstance == null) {
+               if (creationalContext == null) {
+                   return null;
+               } else {
+                   contextualInstance = new ContextualInstance<T>(
                         bean.create(creationalContext), creationalContext);
-                addBeanInstance(bean, contextualInstance);
+                   addBeanInstance(bean, contextualInstance);
+               }
             }
             return contextualInstance.getInstance();
         }
```

**Comment by HRE** [comment]
Ooops... duplicate (#1) & old Version...
