### ISSUE TITLE
NPE in ApplicationBeanStore when Window has no application anymore

### ISSUE THREAD

**Issue by CodingFabian** [tomivirkki/cdiutils#6]
```
Caused by: java.lang.NullPointerException: null
        at     org.vaadin.virkki.cdiutils.application.VaadinContext$ApplicationBeanStore.getWindowBeanStore(VaadinContext.java:144) ~[VaadinContext$ApplicationBeanStore.class:1.0.0]
        at org.vaadin.virkki.cdiutils.application.VaadinContext$ApplicationBeanStore.dereferenceContext(VaadinContext.java:165) ~[VaadinContext$ApplicationBeanStore.class:1.0.0]
        at org.vaadin.virkki.cdiutils.application.AbstractCdiApplication.dereferenceContext(AbstractCdiApplication.java:130) ~[AbstractCdiApplication.class:1.0.0]
```

**Comment by tomivirkki** [comment]
That's odd. Are you using the newest version? There's a null check on line 143 that should make NPE's not possible on line 144

**Comment by CodingFabian** [comment]
oh, as you can see from the stacktrace version info at the end of the line i was using 1.0 at that time.

The line which was NPEing, is now 156. The check which checks if key == main window. but main window cannot be retrieved, because the app is null.

**Comment by tomivirkki** [comment]
Can you describe the steps to reproduce this issue. I'm trying with the latest version but can't make it happen
